# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
